### ISSUE TITLE
strokeWidth issues in IE

### ISSUE THREAD

**Issue by kplese** [kimmobrunfeldt/progressbar.js#152] opened 2016-10-17 09:52 UTC
Hi!

During our development we have discovered an issue when strokeWidth is larger than 6.
Please take a look at this fiddle:
https://jsfiddle.net/kdf6kbra/

If you open it in IE it doesn't work, but if you open it in Chrome or FF, everything works fine.

Otherwise, thank you for a great plugin! :+1:

**Comment by kimmobrunfeldt** [comment] 2016-10-17 10:36
Thanks for reporting. This is duplicate of https://github.com/kimmobrunfeldt/progressbar.js/issues/79. I know this sucks. This has been reported so many times I'll now report the bug to IE/Edge browser team. Let's continue discussion in the other issue.

**Closed by kimmobrunfeldt** 2016-10-17 10:36 UTC
