### ISSUE TITLE
Outline instead of trail

### ISSUE THREAD

**Issue by sebu10n** [kimmobrunfeldt/progressbar.js#155] opened 2016-11-03 13:39 UTC
@kimmobrunfeldt Is it possible to make an outline instead of a trail line in the background? It should look like this:

![image](https://cloud.githubusercontent.com/assets/8061795/19967761/fc59234e-a1d1-11e6-9a3f-fc411e09c647.png)

If it is not implemented yet, would it be possible to do so?

**Comment by anudeep3998** [comment] 2016-11-09 23:19
I'm trying to work exactly on that. Seem to have got part of it done. One question though, how is the image you have an outline? It just looks like a trail with a gray color.

**Comment by sebu10n** [comment] 2016-11-10 07:31
This image is from PhotoShop and only shows how it should look like.

A trail would be only one (thin) line in the middle. I need a thin line at the inner radius and one thin line at the outer radius.

**Comment by anudeep3998** [comment] 2016-11-10 07:41
Yes,  I understand.  I've made the changes necessary and made a pull request.  Before it gets aliens, if you want to use it,  you can check out the changelist I submitted. 
On Nov 10, 2016 2:31 AM, sebu10n <notifications@github.com> wrote:This image is from PhotoShop and only shows how it should look like.

A trail would be only one (thin) line in the middle. I need a thin line at the inner radius and one thin line at the outer radius.

**Comment by sebu10n** [comment] 2016-11-11 08:11
Great! That's it!

**Comment by kimmobrunfeldt** [comment] 2016-12-07 14:50
Good idea. Could you also achieve this effect by painting a thick trail path as gray and having the progress path as white?

**Comment by anudeep3998** [comment] 2016-12-07 19:40
@kimmobrunfeldt We could. The image in the issue can be reproduced. 

Though with an outline , we can achieve an effect where the progress path can cover up the completed part. If we just try using the trail, we would have a permanent outline outside the progress path. I'm not sure I'm putting this across correctly.  Also , we get an added benefit of using a different color and thickness for the outline. 

This image might give you a better idea.

![capture5](https://cloud.githubusercontent.com/assets/5004036/20983604/1a8e8754-bc8b-11e6-8f70-a083a235662e.PNG)

**Comment by kimmobrunfeldt** [comment] 2018-05-28 13:56
I'm closing this issue. To me this doesn't seem that common use-case and it's totally possible to make custom Shapes because the Shape is also exported. With these pieces you can make a custom CircleWithOutline progress bar.

**Closed by kimmobrunfeldt** 2018-05-28 13:56 UTC
