### ISSUE TITLE
Browser(IE) Related Issue

### ISSUE THREAD

**Issue by SachinThakur** [kimmobrunfeldt/progressbar.js#241] opened 2019-04-04 09:25 UTC
Hi ,
This works perfectly on IE ( Version : 11 ) browser but when i increased strokeWidth,trailWidth parameter value more than 8 then its not work in IE browser while works in chrome and mozila.

Thanks,
Sachin

**Comment by kimmobrunfeldt** [comment] 2019-10-28 14:43
Hi, this is indeed very strange bug. Duplicate of https://github.com/kimmobrunfeldt/progressbar.js/issues/79

**Closed by kimmobrunfeldt** 2019-10-28 14:43 UTC
