### ISSUE TITLE
IE11- not rendering progress bar correctly initially

### ISSUE THREAD

**Issue by the14thgod** [kimmobrunfeldt/progressbar.js#163] opened 2017-01-11 17:37 UTC
I'm running into an issue where IE11 and below is not rendering the full progress bar and I can't figure out why. Upon clicking on the SVG the full SVG appears correctly. Attached is an image of what it is doing on top in IE and what all other browsers render at the bottom.

![ie-issue](https://cloud.githubusercontent.com/assets/5037436/21859189/5ae541ae-d7f1-11e6-93a3-9ee55f698b4d.jpg)

Here is my JS:
`var oProgressBars = $('.progressbar');

// Verify progress bars exist before iniating progressbar.js
if(oProgressBars.length > 0){

	// Loop thru all progress bars
	$.each(oProgressBars, function(i){
		var oThis = $(this),
			oCanvas = oThis.find('div.canvas'),
			oPath = oCanvas.find('.js-bar'),
			oNumber = oThis.find('span.number'),
			iValue = parseInt(oCanvas.data('value')),
			iMax = parseInt(oCanvas.data('max')),
			iPercentage = iValue / iMax,
			bar = new ProgressBar.Path(document.getElementById(oPath.attr('id')), {
				easing: 'easeInOut',
				duration: 1000,
				// Set default step function for all animate calls
				step: function(state, bar){
					var value = Math.round(bar.value() * 100).toFixed(0);

					// Set Text
					oNumber.text(iMax - value);
				}
			});

		bar.animate(iPercentage); // Number from 0.0 to 1.0
	});
}`

And here is my HTML:
`[div class="progressbar"]
	[div id="js-progressbar1-1" class="canvas" data-max="100" data-value="80"]
		[!-- SVG --]
		[svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 239.62 207.99"]
			[title]belt life remaining[/title]
			[path d="M537.4,311.65a107.81,107.81,0,1,0-152.57,0" transform="translate(-341.31 -115.66)" fill="none" stroke="#252525" stroke-linecap="round" stroke-miterlimit="10" stroke-width="24"/]
			[path id="svg-bar1-1" class="js-bar" d="M384.83,311.65a107.81,107.81,0,1,1,152.57,0" transform="translate(-341.31 -115.66)" fill="none" stroke="#cc0000" stroke-linecap="round" stroke-miterlimit="10" stroke-width="24"/]
		[/svg]
		[!-- End SVG --]
	[/div]
	[div class="text"]
		[span class="number"]0[/span]
		[span class="unit"]hours[/span]
		[span class="icon belt"][/span]
	[/div]
[/div]`
Now in a readable format...
![html](https://cloud.githubusercontent.com/assets/5037436/21859446/41228456-d7f2-11e6-8600-2821bc3f3413.jpg)

I have a temporary fix in place to cut out the animation by calculating the value myself but the client would prefer the bar to be animated.

Thanks for this plugin and any and all help solving this issue.
Justin

**Comment by brunolarouche** [comment] 2017-03-22 15:21
Seems like a duplicated bug, seems pretty much the same at this one https://github.com/kimmobrunfeldt/progressbar.js/issues/79, no?

**Comment by the14thgod** [comment] 2017-03-22 18:10
It might be but I thought when I tested I was getting different results from that ticket thus why I posted. I honestly don't remember and currently I just have my fix in place. You have more experience with this so if to you it looks to be the same I'm fine with you closing this as a duplicate.

**Comment by kimmobrunfeldt** [comment] 2017-09-09 15:14
I believe this is indeed duplicate of #79. I'll keep this open anyways.

**Comment by kimmobrunfeldt** [comment] 2018-05-28 14:01
Closing, let's move to #79.

**Closed by kimmobrunfeldt** 2018-05-28 14:01 UTC
Labels: bug, help wanted, not trivial, pull request welcome
