### ISSUE TITLE
Keeping circle within container

### ISSUE THREAD

**Issue by laszlof** [kimmobrunfeldt/progressbar.js#44] opened 2015-01-30 20:58 UTC
Is there some trick to keeping the circle from drawing outside of the container? I'm using this on a mobile app I am working on, and seems like if I dont set an explicit width/height for the container, the circle ends up overflowing out of the div.

**Comment by kimmobrunfeldt** [comment] 2015-01-30 21:04
You can set the svg explicitly to 100% width of the container for example

    .container > svg {
        width: 100%;
    }

Then it doesn't overflow the container, that would probably be a good default though. I have to consider if the library itself would set the svg width

**Comment by laszlof** [comment] 2015-01-30 21:10
Cheers! Perfect. That was really annoying me. I agree on the default thing. Perhaps providing an easy way to override it without mucking with the styles might be an option as well.

Thanks for your quick reply.

**Comment by kimmobrunfeldt** [comment] 2015-02-02 07:25
The problem is, should I set width or height for the svg to be 100%? Or both?

**Comment by kimmobrunfeldt** [comment] 2015-02-17 12:29
I'll close this for now since this [is documented](https://github.com/kimmobrunfeldt/progressbar.js#shapecontainer-options) and I don't know how to implement this in a way that it would be intuitive in all cases. Depending on the situation, you might want the SVG to fill the container in different ways. I'll leave that decision to the user.

If someone has a good idea how to implement this, I'll reopen.

**Comment by kimmobrunfeldt** [comment] 2015-02-17 12:30
Initial idea: SVG would be always `width: 100%;` of the container and it would be documented how to override this default. It would need some changes to the API though

**Closed by kimmobrunfeldt** 2015-02-17 12:29 UTC
